<a href="https://colab.research.google.com/github/naokityokoyama/Machine_Learning/blob/master/DBSCAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import MeanShift
from sklearn.metrics import silhouette_score

In [4]:
df = pd.read_csv('/content/Wine.csv')
df.head()

Alcohol  Malic_Acid   Ash  ...  OD280  Proline  Customer_Segment
0    14.23        1.71  2.43  ...   3.92     1065                 1
1    13.20        1.78  2.14  ...   3.40     1050                 1
2    13.16        2.36  2.67  ...   3.17     1185                 1
3    14.37        1.95  2.50  ...   3.45     1480                 1
4    13.24        2.59  2.87  ...   2.93      735                 1

[5 rows x 14 columns]

## Normalizar os dados


In [7]:
minmax = MinMaxScaler()
mimmax_transform = minmax.fit_transform(df)
df_novo =  pd.DataFrame(columns=[df.columns], data=mimmax_transform)

df_novo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   (Alcohol,)               178 non-null    float64
 1   (Malic_Acid,)            178 non-null    float64
 2   (Ash,)                   178 non-null    float64
 3   (Ash_Alcanity,)          178 non-null    float64
 4   (Magnesium,)             178 non-null    float64
 5   (Total_Phenols,)         178 non-null    float64
 6   (Flavanoids,)            178 non-null    float64
 7   (Nonflavanoid_Phenols,)  178 non-null    float64
 8   (Proanthocyanins,)       178 non-null    float64
 9   (Color_Intensity,)       178 non-null    float64
 10  (Hue,)                   178 non-null    float64
 11  (OD280,)                 178 non-null    float64
 12  (Proline,)               178 non-null    float64
 13  (Customer_Segment,)      178 non-null    float64
dtypes: float64(14)
memory usag

## DBSCAN  
Clusterização Espacial Baseada em Densidade de Aplicações com Ruído

In [8]:
dbscan = DBSCAN(eps=1.31, min_samples=15, metric='manhattan') 
#eps = distancia maxima entre 2 pontos para que eles possam ser tornar vizinhos 
#min_samples = numero minimos de pontos para que possa forma um cluster
#metric = metrica

In [10]:
cluster = dbscan.fit(df_novo)

In [11]:
cluster.labels_ #valores negativos são ruidos

array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1,  0, -1,  0, -1,  0, -1,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,
        1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  2, -1,  2, -1,  2,
       -1, -1,  2, -1, -1,  2, -1, -1,  2,  2, -1,  2,  2,  2, -1, -1, -1,
        2, -1,  2,  2, -1, -1, -1,  2,  2,  2,  2,  2, -1,  2,  2,  2, -1,
        2,  2,  2,  2,  2,  2,  2,  2])

In [18]:
np.unique(cluster.labels_)

array([0, 1])

## Meanshift

In [17]:
meanshift = MeanShift()
cluster = meanshift.fit(df_novo)
cluster.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

## Silhouette Score

In [20]:
silhouette_score(df_novo, cluster.labels_, metric='euclidean')

0.20758352839192912